POST https://fullstack-open-part4.onrender.com/api/blogposts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvZ2lubmFtZSIsImlkIjoiNjY4ZGZlNjk1YzFhMTU0YTNiMDFlNjdmIiwiaWF0IjoxNzIwNTgzMzM4fQ.ptoYLeaGAtbjOVgEEGcu5b94lMqSUnNAH7Fj1MMJbxI

{
  "title": "Testiblogipostaus with id",
  "author": "Seppo Blogipostinen",
  "url": "www.google.fi",
  "likes": 1,
  "userId": "668df5eda341e53e98f685f2"
}

